#!/usr/bin/env python3
"""Copy the lending metadata, minus the parts only an embedded host can serve.

The suite's whole point is that both hosts serve the *same* declarations. One
kind cannot be shared: an action declared without a `handler` is resolved
in-process by a function the embedding program registered, and `donat-server`
refuses to start rather than mount a field it could never answer. That refusal
is correct — a field in the schema that never works is worse than a failed
boot — so the engine stand is given a copy with those actions removed instead.

Everything else, including every command, rule, permission and table, is copied
byte for byte: what the suite compares must not be a rewrite of what it runs.

    engine_metadata.py <source-metadata-dir> <destination-dir>
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

import yaml


def strip_embedded_only_actions(actions_file: Path) -> int:
    """Remove handler-less actions in place. Returns how many were removed."""
    document = yaml.safe_load(actions_file.read_text()) or {}
    actions = document.get("actions") or []
    kept = [a for a in actions if a.get("definition", {}).get("handler")]
    removed = len(actions) - len(kept)
    if removed == 0:
        return 0

    document["actions"] = kept
    # `custom_types` stays. An object type no action returns is inert in the
    # generated schema, and dropping it would mean deciding which types were
    # only ever reachable through a removed action — a rewrite, not a copy.
    actions_file.write_text(
        "# Generated by tests-system-lending/engine_metadata.py — do not edit.\n"
        "# Handler-less actions are removed: only an embedded host can resolve\n"
        "# them, and the standalone engine refuses to mount a field it cannot\n"
        "# answer.\n" + yaml.safe_dump(document, sort_keys=False)
    )
    return removed


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    source, destination = Path(argv[1]), Path(argv[2])
    if not source.is_dir():
        print(f"no metadata directory at {source}", file=sys.stderr)
        return 1

    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(source, destination)

    removed = 0
    for actions_file in destination.rglob("actions.yaml"):
        removed += strip_embedded_only_actions(actions_file)
    print(f"engine metadata written to {destination} ({removed} embedded-only action(s) removed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
