// Code generated by donat codegen go; DO NOT EDIT.

package golden

import (
	"encoding/json"
	"time"

	"github.com/shopspring/decimal"
)

type OrderStatus string

const (
	OrderStatusOpen OrderStatus = "open"
	OrderStatusPaid OrderStatus = "paid"
)

type TestT1 struct {
	C1        int32           `json:"c1"`
	C2        *string         `json:"c2"`
	Amount    decimal.Decimal `json:"amount"`
	Tags      []string        `json:"tags"`
	Status    OrderStatus     `json:"status"`
	CreatedAt time.Time       `json:"created_at"`
	Payload   json.RawMessage `json:"payload"`
}
