//! `donat codegen go`: generate Go row structs from the Postgres catalog.
//!
//! The pure `generate_go` turns a catalog snapshot + the set of tracked
//! tables + an enum-label map into a single gofmt-ready Go source string.
//! It performs no I/O so it is fully snapshot-testable. `run_codegen` wraps
//! it with introspection and file writing.

use std::collections::BTreeMap;
use std::path::Path;

use anyhow::{Context, Result};
use donat_catalog::{Catalog, ColumnInfo};
use tokio_postgres::NoTls;

/// Map of Postgres enum type name -> ordered labels.
pub type EnumMap = BTreeMap<String, Vec<String>>;

/// Tracks which imports the generated file needs.
#[derive(Default)]
struct Needs {
    time: bool,
    decimal: bool,
    json: bool,
}

/// Go type for a Postgres `typname`. Records needed imports in `needs`.
/// `enums` lets enum-typed columns resolve to their generated alias name.
fn map_type(pg_type: &str, enums: &EnumMap, needs: &mut Needs) -> String {
    // Array types: pg `typname` is the element name with a leading underscore.
    if let Some(elem) = pg_type.strip_prefix('_') {
        return format!("[]{}", map_type(elem, enums, needs));
    }
    if enums.contains_key(pg_type) {
        return pascal(pg_type);
    }
    match pg_type {
        "int2" => "int16".into(),
        "int4" => "int32".into(),
        "int8" => "int64".into(),
        "float4" | "float8" => "float64".into(),
        "numeric" => {
            needs.decimal = true;
            "decimal.Decimal".into()
        }
        "text" | "varchar" | "bpchar" | "name" => "string".into(),
        "bool" => "bool".into(),
        "uuid" => "string".into(),
        "timestamptz" | "timestamp" | "date" => {
            needs.time = true;
            "time.Time".into()
        }
        "json" | "jsonb" => {
            needs.json = true;
            "json.RawMessage".into()
        }
        _ => {
            // Unknown: never fail codegen, fall back to raw JSON.
            needs.json = true;
            "json.RawMessage".into()
        }
    }
}

/// snake_case / lower_case identifier -> PascalCase Go identifier.
fn pascal(s: &str) -> String {
    s.split(|c| c == '_' || c == ' ')
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut ch = p.chars();
            match ch.next() {
                Some(f) => f.to_uppercase().collect::<String>() + &ch.as_str().to_lowercase(),
                None => String::new(),
            }
        })
        .collect()
}

/// Go type name for a table. `public` is unprefixed; other schemas are
/// schema-prefixed so cross-schema same-named tables never collide.
fn go_type_name(schema: &str, name: &str) -> String {
    if schema == "public" {
        pascal(name)
    } else {
        format!("{}{}", pascal(schema), pascal(name))
    }
}

/// A column's Go type, made a pointer when the column is nullable.
fn field_type(col: &ColumnInfo, enums: &EnumMap, needs: &mut Needs) -> String {
    let base = map_type(&col.pg_type, enums, needs);
    if col.nullable {
        format!("*{base}")
    } else {
        base
    }
}

/// Generate Go source for `tracked` tables `(schema, name)` found in `catalog`.
pub fn generate_go(
    catalog: &Catalog,
    tracked: &[(String, String)],
    enums: &EnumMap,
    package: &str,
) -> String {
    let mut needs = Needs::default();
    let mut body = String::new();

    // Enum type aliases + label constants, deterministic by type name.
    for (enum_name, labels) in enums {
        let go_name = pascal(enum_name);
        body.push_str(&format!("type {go_name} string\n\n"));
        body.push_str("const (\n");
        for label in labels {
            body.push_str(&format!(
                "\t{}{} {} = \"{}\"\n",
                go_name,
                pascal(label),
                go_name,
                label,
            ));
        }
        body.push_str(")\n\n");
    }

    for (schema, name) in tracked {
        let Some(table) = catalog.tables.get(&format!("{schema}.{name}")) else {
            eprintln!("warning: tracked table {schema}.{name} not found in catalog; skipped");
            continue;
        };
        body.push_str(&format!(
            "type {} struct {{\n",
            go_type_name(&table.schema, &table.name)
        ));
        for c in &table.columns {
            body.push_str(&format!(
                "\t{} {} `json:\"{}\"`\n",
                pascal(&c.name),
                field_type(c, enums, &mut needs),
                c.name,
            ));
        }
        body.push_str("}\n\n");
    }

    let mut out = String::new();
    out.push_str("// Code generated by donat codegen go; DO NOT EDIT.\n\n");
    out.push_str(&format!("package {package}\n\n"));

    let mut imports: Vec<&str> = Vec::new();
    if needs.json {
        imports.push("\"encoding/json\"");
    }
    if needs.time {
        imports.push("\"time\"");
    }
    if needs.decimal {
        imports.push("\"github.com/shopspring/decimal\"");
    }
    if !imports.is_empty() {
        out.push_str("import (\n");
        for imp in imports {
            out.push_str(&format!("\t{imp}\n"));
        }
        out.push_str(")\n\n");
    }
    out.push_str(&body);
    out
}

/// SQL: every enum type's labels in sort order, user schemas only.
const ENUMS_SQL: &str = "\
SELECT t.typname, e.enumlabel \
FROM pg_type t \
JOIN pg_enum e ON e.enumtypid = t.oid \
JOIN pg_namespace n ON t.typnamespace = n.oid \
WHERE n.nspname NOT IN ('pg_catalog', 'information_schema') \
ORDER BY t.typname, e.enumsortorder";

async fn fetch_enums(client: &tokio_postgres::Client) -> Result<EnumMap> {
    let rows = client.query(ENUMS_SQL, &[]).await.context("querying pg_enum")?;
    let mut map = EnumMap::new();
    for row in rows {
        let typname: String = row.get(0);
        let label: String = row.get(1);
        map.entry(typname).or_default().push(label);
    }
    Ok(map)
}

/// Collect tracked `(schema, name)` pairs from the metadata directory.
/// `QualifiedTable::Name` defaults to the `public` schema.
fn tracked_tables(metadata: &donat_metadata::Metadata) -> Vec<(String, String)> {
    let mut out = Vec::new();
    for source in &metadata.sources {
        for t in &source.tables {
            out.push((t.table.schema().to_string(), t.table.name().to_string()));
        }
    }
    out
}

/// Introspect the database, generate Go, and write `<out_dir>/donat_gen.go`.
pub async fn run_codegen(
    database_url: &str,
    metadata_dir: &Path,
    out_dir: &Path,
    package: &str,
) -> Result<()> {
    let metadata = donat_metadata::load_metadata_dir(metadata_dir)
        .with_context(|| format!("loading metadata from {}", metadata_dir.display()))?;
    let tracked = tracked_tables(&metadata);

    let (client, conn) = tokio_postgres::connect(database_url, NoTls)
        .await
        .context("connecting to database for codegen")?;
    let conn = tokio::spawn(async move { conn.await });
    let catalog = donat_catalog::introspect(&client)
        .await
        .context("introspecting database")?;
    let enums = fetch_enums(&client).await?;
    conn.abort();

    let source = generate_go(&catalog, &tracked, &enums, package);
    std::fs::create_dir_all(out_dir)
        .with_context(|| format!("creating out dir {}", out_dir.display()))?;
    let path = out_dir.join("donat_gen.go");
    std::fs::write(&path, source).with_context(|| format!("writing {}", path.display()))?;
    gofmt_in_place(&path);
    tracing::info!(path = %path.display(), tables = tracked.len(), "Go types generated");
    Ok(())
}

/// Emit the serialized `{ "metadata": <Metadata>, "catalog": <Catalog> }`
/// JSON that the embedded wasm-core host (`donat.New` via `core_init`)
/// consumes. Introspection happens here, deploy-time and host-side — exactly
/// the snapshot the Go SDK hands to the wasm core (Spec 004). This is the
/// "prepare the core config" step a Go host runs before serving.
pub async fn dump_core_config(database_url: &str, metadata_dir: &Path, out: &Path) -> Result<()> {
    let metadata = donat_metadata::load_metadata_dir(metadata_dir)
        .with_context(|| format!("loading metadata from {}", metadata_dir.display()))?;

    let (client, conn) = tokio_postgres::connect(database_url, NoTls)
        .await
        .context("connecting to database for core-config dump")?;
    let conn = tokio::spawn(async move { conn.await });
    let catalog = donat_catalog::introspect(&client)
        .await
        .context("introspecting database")?;
    conn.abort();

    let cfg = serde_json::json!({ "metadata": metadata, "catalog": catalog });
    let json = serde_json::to_string_pretty(&cfg).context("serializing core config")?;
    if let Some(parent) = out.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating out dir {}", parent.display()))?;
    }
    std::fs::write(out, json).with_context(|| format!("writing {}", out.display()))?;
    tracing::info!(path = %out.display(), tables = catalog.tables.len(), "core config written");
    Ok(())
}

/// Best-effort `gofmt -w` on the generated file. The generated source is
/// already valid Go; gofmt only aligns struct columns. If gofmt is not on
/// PATH we leave the valid-but-unaligned file and log a hint.
fn gofmt_in_place(path: &Path) {
    match std::process::Command::new("gofmt").arg("-w").arg(path).status() {
        Ok(s) if s.success() => {}
        Ok(s) => tracing::warn!(status = ?s, "gofmt exited non-zero; left unformatted (valid) Go"),
        Err(_) => tracing::info!("gofmt not found on PATH; generated valid Go is left unformatted"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use donat_catalog::TableInfo;

    fn col(name: &str, pg_type: &str, nullable: bool) -> ColumnInfo {
        ColumnInfo {
            name: name.into(),
            pg_type: pg_type.into(),
            nullable,
            has_default: false,
        }
    }

    fn catalog_with(table: TableInfo) -> Catalog {
        let mut tables = BTreeMap::new();
        tables.insert(format!("{}.{}", table.schema, table.name), table);
        Catalog {
            tables,
            functions: BTreeMap::new(),
        }
    }

    #[test]
    fn scalars_basic() {
        let t = TableInfo {
            schema: "public".into(),
            name: "test_t1".into(),
            columns: vec![
                col("c1", "int4", false),
                col("c2", "text", false),
                col("ok", "bool", false),
            ],
            primary_key: vec![],
            foreign_keys: vec![],
        };
        let cat = catalog_with(t);
        let out = generate_go(
            &cat,
            &[("public".into(), "test_t1".into())],
            &EnumMap::new(),
            "donat_gen",
        );
        insta::assert_snapshot!(out);
    }

    #[test]
    fn scalars_all_types() {
        let t = TableInfo {
            schema: "public".into(),
            name: "wide".into(),
            columns: vec![
                col("a", "int2", false),
                col("b", "int8", false),
                col("amount", "numeric", false),
                col("ratio", "float8", false),
                col("created_at", "timestamptz", false),
                col("uid", "uuid", false),
                col("payload", "jsonb", false),
                col("weird", "tsvector", false), // unknown -> json.RawMessage
            ],
            primary_key: vec![],
            foreign_keys: vec![],
        };
        let cat = catalog_with(t);
        let out = generate_go(
            &cat,
            &[("public".into(), "wide".into())],
            &EnumMap::new(),
            "donat_gen",
        );
        insta::assert_snapshot!(out);
    }

    #[test]
    fn nullable_columns_become_pointers() {
        let t = TableInfo {
            schema: "public".into(),
            name: "nul".into(),
            columns: vec![
                col("id", "int4", false),
                col("note", "text", true),
                col("amount", "numeric", true),
            ],
            primary_key: vec![],
            foreign_keys: vec![],
        };
        let cat = catalog_with(t);
        let out = generate_go(
            &cat,
            &[("public".into(), "nul".into())],
            &EnumMap::new(),
            "donat_gen",
        );
        insta::assert_snapshot!(out);
    }

    #[test]
    fn array_columns_become_slices() {
        let t = TableInfo {
            schema: "public".into(),
            name: "arr".into(),
            columns: vec![
                col("ids", "_int4", false),  // int4[] -> []int32
                col("tags", "_text", true),  // nullable text[] -> *[]string
            ],
            primary_key: vec![],
            foreign_keys: vec![],
        };
        let cat = catalog_with(t);
        let out = generate_go(
            &cat,
            &[("public".into(), "arr".into())],
            &EnumMap::new(),
            "donat_gen",
        );
        insta::assert_snapshot!(out);
    }

    #[test]
    fn enum_types_emit_alias_and_consts() {
        let t = TableInfo {
            schema: "public".into(),
            name: "task".into(),
            columns: vec![
                col("id", "int4", false),
                col("status", "task_status", false), // enum
                col("prev", "task_status", true),     // nullable enum -> pointer
            ],
            primary_key: vec![],
            foreign_keys: vec![],
        };
        let cat = catalog_with(t);
        let mut enums = EnumMap::new();
        enums.insert(
            "task_status".into(),
            vec!["open".into(), "in_progress".into(), "done".into()],
        );
        let out = generate_go(
            &cat,
            &[("public".into(), "task".into())],
            &enums,
            "donat_gen",
        );
        insta::assert_snapshot!(out);
    }

    #[test]
    fn multi_schema_tables_disambiguated() {
        let mut tables = BTreeMap::new();
        for (schema, name) in [("public", "user"), ("auth", "user")] {
            tables.insert(
                format!("{schema}.{name}"),
                TableInfo {
                    schema: schema.into(),
                    name: name.into(),
                    columns: vec![col("id", "int4", false)],
                    primary_key: vec![],
                    foreign_keys: vec![],
                },
            );
        }
        let cat = Catalog {
            tables,
            functions: BTreeMap::new(),
        };
        let tracked = vec![
            ("public".into(), "user".into()),
            ("auth".into(), "user".into()),
        ];
        let out = generate_go(&cat, &tracked, &EnumMap::new(), "donat_gen");
        insta::assert_snapshot!(out);
    }
}
